### ISSUE TITLE
Improve History display of multiple workouts on the same day

### ISSUE THREAD

**Issue by nano9g** [timfraedrich/OutRun#3]
**Is your feature request related to a problem? Please describe.**
Currently the History view displays the same information header (Today, Yesterday, etc.) above every workout, even when there are multiple workouts on the same day. In my opinion, this adds visual noise without much benefit.

**Describe the solution you'd like**
I could see two ways to address this.
1.  A single header for each day with all that day's workouts below:
> **Today**
> [Workout 1]
> [Workout 2]

2. Continue to have a header for each workout, but add the time.
> **Today 7:30 AM**
> [Workout 1]
> **Today 3:00 PM**
> [Workout 2]

I'm personally partial to option 1 (although I would like to see start time displayed somewhere in the History view, I'm not sure the header is the right place for it).

I'd be happy to mock this up if the text-based examples aren't clear. Thanks!

**Comment by timfraedrich** [comment]
This is actually how it has been some time ago and I myself liked it better that way as well.

The reason I had to change it was the introduction of the filter. When changing something in it there sometimes were empty sections or the app even crashed because it tried to read content that wasn't there.

That being said, I will look into it again and try to find a solution.
