### ISSUE TITLE
What’s pedal strokes for manual cycling workout

### ISSUE THREAD

**Issue by zinwalin** [timfraedrich/OutRun#64]
![image](https://user-images.githubusercontent.com/5416196/118582009-36c12500-b7c5-11eb-901a-d2e8e33da813.png)

**Comment by timfraedrich** [comment]
While recording a workout OutRun also saves the steps you make, on a bicycle you do not do steps but pedal strokes, so those are saved instead. This metric is not very accurate though, since you would need to keep your phone in your pocket during the workout.

On a manual entry you can also provide this attribute.

**Comment by zinwalin** [comment]
> While recording a workout OutRun also saves the steps you make, on a bicycle you do not do steps but pedal strokes, so those are saved instead. This metric is not very accurate though, since you would need to keep your phone in your pocket during the workout.
> 
> On a manual entry you can also provide this attribute.

what's the proper pedal strokes value should I set when manual input.

**Comment by timfraedrich** [comment]
You can just leave this field blank, it is not required to input anything.
